name: taxiapp
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.0

  # state management
  stacked: ^1.7.6
  stacked_hooks: ^0.1.3
  flutter_hooks: ^0.12.0
  # navigation
  auto_route: ^0.6.9
  # inversion of control
  get_it: ^5.0.3
  injectable: ^1.0.5

  dio: ^3.0.10
  dio_cookie_manager: ^1.0.0
  morpheus: ^1.2.2+1
  toast: ^0.1.5
  path_provider: ^1.6.11
  retry: ^3.0.1
  esys_flutter_share: ^1.0.2
  shared_preferences: ^0.5.12+4
  package_info: ^0.4.3+2
  url_launcher: ^5.5.0
  permission_handler: ^5.0.1+1
  flutter_svg: ^0.18.0
  google_fonts: ^1.1.0
  cached_network_image: ^2.2.0+1
  json_annotation: ^3.1.1
  flutter_secure_storage: ^3.3.3
  image_picker: ^0.6.7+4
  flutter_native_image: ^0.0.5+2
  flutter_exif_rotation: ^0.2.7
  flutter_translate: ^1.6.0
  flutter_translate_annotations: ^1.0.1
  
  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4+1
  cloud_firestore: ^0.14.4
  google_sign_in: ^4.5.6
  google_maps_flutter: ^1.0.6
  geolocator: ^5.3.2+2
  google_polyline_algorithm: ^2.0.0

  flutter_facebook_login: ^3.0.0
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.15.4
  build_runner: ^1.10.2
  auto_route_generator: ^0.6.9
  injectable_generator: ^1.0.5
  flutter_translate_gen: ^1.2.4
  json_serializable: ^3.5.0
  pedantic: ^1.9.2

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/icons/
    - assets/map_theme/
